<?php

namespace AtelierBundle\Repository;

/**
 * AtelierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtelierRepository extends \Doctrine\ORM\EntityRepository
{
}
